### ISSUE TITLE
Stopped working after update to EdgeOS v1.10.8

### ISSUE THREAD

**Issue by ptz0n** [britannic/blacklist#7] opened 2019-01-07 21:16 UTC
I recently updated my ERPoe-5 to EdgeOS v1.10.8 and found that blacklist was no longer doing its magic.

First, I tried configuring of a new domain:

```bash
$ configure
# set service dns forwarding blacklist domains exclude bing.com           
The specified configuration node is not valid
Set failed
```

Second, I tried updating but was already on the current version.

```
$ sudo apt-get update && sudo apt-get upgrade edgeos-dnsmasq-blacklist
…
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Finally, tried reinstalling, which did the trick and also included my previously included domains.

__Question:__ Should updating EdgeOS require reinstall of blacklist?

**Comment by britannic** [comment] 2019-01-07 21:39
Unless you set up automatic reinstallation in the /config (persistent disk space), then yes, upgrading your router will require a new install of blacklisting, since the Edge Router upgrade creates and installs a brand new image.

**Comment by britannic** [comment] 2019-01-07 21:39
Closing issue, since it is caused by 3rd party upgrades.

**Closed by britannic** 2019-01-07 21:39 UTC
